name: Check Markdown links

on: push

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Link Checker
      uses: peter-evans/link-checker@v1.0.0
      with:
        args: -v -r *
        
